-- MCP Servers table for storing server configurations
CREATE TABLE IF NOT EXISTS mcp_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    url VARCHAR(1024) NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'http',
    timeout INTEGER NOT NULL DEFAULT 30,
    enabled BOOLEAN NOT NULL DEFAULT true,
    description TEXT,
    image_icon VARCHAR(512),
    policy_id VARCHAR(255),
    tags TEXT, -- JSON array stored as string
    tools TEXT, -- JSON array stored as string
    metadata TEXT, -- JSON object stored as string
    auth_method VARCHAR(50),
    auth_location VARCHAR(50),
    auth_name VARCHAR(255),
    auth_format VARCHAR(255),
    auth_prefix VARCHAR(255),
    auth_credential_ref VARCHAR(255),
    auth_credential VARCHAR(1024), -- For direct credentials (encrypted in production)
    auth_client_id VARCHAR(255),
    auth_client_secret VARCHAR(512),
    auth_token_url VARCHAR(1024),
    auth_scopes TEXT,
    auth_audience VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mcp_servers_name ON mcp_servers(name);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_enabled ON mcp_servers(enabled);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_type ON mcp_servers(type);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_policy_id ON mcp_servers(policy_id);
